Idea_Database_Interface/Controllers/BonosController.cs
using Idea_Database_Interface.Data.UnitOfWork;
using Idea_Database_Interface.Models;
using Idea_Database_Interface.Services;
using Idea_Database_Interface.Viewmodels;
using IronXL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PagedList;
using System.Data;
using System.Drawing.Text;
using System.Globalization;
using System.IO;

namespace Idea_Database_Interface.Controllers
{
    [Authorize(Roles = "admin")]
    public class BonosController : Controller
    {
        private readonly IUnitOfWork _uow;
        public BonosController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public IActionResult Index(string searchString, string filterSelect, int? page, DateTime? filterDate)
        {
            List<string> options = new();
            options.Add("Nombre");
            options.Add("Teléfono");
            options.Add("Correo");
            options.Add("DNI");
            options.Add("Localizador");
            SelectList filterOptions = new SelectList(options);
            IEnumerable<Bonos> bonos = _uow.BonosRepository.GetAll().OrderBy(x => x.Date);

            //filters based on the input of the searchstring and the selected filter
            //if the search string is empty it will just show all the companies
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                switch (filterSelect)
                {
                    case "Nombre":
                        bonos = bonos.Where(x => x.Nombre.ToLower().Contains(searchString) || x.PrimerApellido.ToLower().Contains(searchString) || x.SegunodApellido.ToLower().Contains(searchString)).ToList();
                        break;
                    case "Teléfono":
                        bonos = bonos.Where(x => x.Teléfono.Contains(searchString)).ToList();
                        break;
                    case "Correo":
                        bonos = bonos.Where(x => x.Correo.ToLower().Contains(searchString)).ToList();
                        break;
                    case "DNI":
                        bonos = bonos.Where(x => x.DNI.ToLower().Contains(searchString)).ToList();
                        break;
                    case "Localizador":
                        bonos = bonos.Where(x => x.Localizador.ToLower().Contains(searchString)).ToList();
                        break;
                    default:
                        break;
                }

            }
            if (filterDate != null && filterDate != DateTime.MinValue)
                bonos = bonos.Where(x => x.Date.Date.Equals(filterDate.Value.Date)).ToList();
            //This is to prevent the searchbox from being erased
            ViewBag.SearchString = searchString;
            //Here you can change the amount of items on a page
            int pageSize = 10;
            int pageNumber = page ?? 1;
            //this is to check if the pagenumber isnt higher than the pagecount
            IPagedList testList = bonos.ToPagedList(1, pageSize);
            if (testList.PageCount < pageNumber)
                pageNumber = testList.PageCount;
            pageNumber = pageNumber < 1 ? 1 : pageNumber;
            BonosListViewModel model = new BonosListViewModel()
            {
                Bonos = bonos.ToPagedList(pageNumber, pageSize),
                FilterOptions = filterOptions,
                PageCount = pageNumber,
                SearchedFilter = filterSelect,
                SearchedString = searchString,
                DateFilter = filterDate.GetValueOrDefault().Date,
            };
            //This resets the pagenumber for the next and previous page buttons
            //Without this you can only change the page once
            //And with this line of code it just works, i dont know how
            ModelState.Clear();
            return View(model);
        }
        public IActionResult Import()
        {
            FileUpload vm = new FileUpload();
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Import(IFormFile fileUpload)
        {
            IQueryable<Bonos> allDbBonos = _uow.BonosRepository.GetAll();
            try
            {
                if (fileUpload != null && fileUpload.Length > 0)
                {
                    var ext = System.IO.Path.GetExtension(fileUpload.FileName);
                    if (ext != ".xls" && ext != ".xlsx")
                        return View(new FileUpload() { AlertMessage = "El archivo no tiene formato .xls o .xlsx" });
                    ExcelToDatabase toDb = new ExcelToDatabase(_uow);
                    await toDb.ImportToDatabaseAsync(fileUpload);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                FileUpload vmError = new FileUpload()
                {
                    AlertMessage = "Error al cargar el archivo"
                };
                return View(vmError);
            }
            FileUpload vm = new FileUpload()
            {
                AlertMessage = "Error al cargar el archivo"
            };
            return View(vm);
        }
        public IActionResult CreateBono()
        {
            BonoCrudViewModel vm = new BonoCrudViewModel();
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> CreateBono(BonoCrudViewModel bono)
        {
            if (ModelState.IsValid)
            {
                Bonos toAdd = new Bonos()
                {
                    Nombre = bono.Nombre,
                    PrimerApellido = bono.PrimerApellido,
                    DNI = bono.DNI,
                    Date = bono.Date + bono.Hours,
                    Direcction = bono.Direcction,
                    NumeroDeBonos = bono.NumeroDeBonos,
                    Correo = bono.Correo,
                    CódigoPostal = bono.CódigoPostal,
                    NúmeroId = bono.NúmeroId,
                    NúmeroId2 = bono.NúmeroId2,
                    SegunodApellido = bono.SegunodApellido,
                    TarjetaNum = bono.TarjetaNum,
                    Teléfono = bono.Teléfono
                };
                _uow.BonosRepository.Create(toAdd);
                await _uow.Save();
                return RedirectToAction("Index");
            }
            return View(bono);
        }
        public async Task<IActionResult> Details(int id)
        {
            Bonos bono = await _uow.BonosRepository.GetById(id);
            BonosDetailsViewModel viewModel = new BonosDetailsViewModel() { Bonos = bono };
            return View(viewModel);
        }
        public async Task<IActionResult> UpdateBono(int id)
        {
            Bonos bono = await _uow.BonosRepository.GetById(id);
            BonoCrudViewModel viewModel = new BonoCrudViewModel()
            {
                Nombre = bono.Nombre,
                PrimerApellido = bono.PrimerApellido,
                DNI = bono.DNI,
                Date = bono.Date,
                Direcction = bono.Direcction,
                NumeroDeBonos = bono.NumeroDeBonos,
                Correo = bono.Correo,
                CódigoPostal = bono.CódigoPostal,
                NúmeroId = bono.NúmeroId,
                NúmeroId2 = bono.NúmeroId2,
                SegunodApellido = bono.SegunodApellido,
                TarjetaNum = bono.TarjetaNum,
                Teléfono = bono.Teléfono,
                Id = bono.Id
            };
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBono(int id, BonoCrudViewModel bono)
        {
            if (ModelState.IsValid)
            {
                Bonos toUpdate = new Bonos()
                {
                    Nombre = bono.Nombre,
                    PrimerApellido = bono.PrimerApellido,
                    DNI = bono.DNI,
                    Date = bono.Date + bono.Hours,
                    Direcction = bono.Direcction,
                    NumeroDeBonos = bono.NumeroDeBonos,
                    Correo = bono.Correo,
                    CódigoPostal = bono.CódigoPostal,
                    NúmeroId = bono.NúmeroId,
                    NúmeroId2 = bono.NúmeroId2,
                    SegunodApellido = bono.SegunodApellido,
                    TarjetaNum = bono.TarjetaNum,
                    Teléfono = bono.Teléfono,
                    Id = id
                };
                _uow.BonosRepository.Update(toUpdate);
                await _uow.Save();
                return RedirectToAction("Index");
            }

            return View(bono);
        }
        public async Task<IActionResult> DeleteBono(int id)
        {
            Bonos toDel = await _uow.BonosRepository.GetById(id);
            _uow.BonosRepository.Delete(toDel);
            await _uow.Save();
            return RedirectToAction("Index");
        }
        public IActionResult ExportDatabase()
        {
            ExportDBDateViewModel vm = new ExportDBDateViewModel()
            {
                From = DateTime.Now.Date,
                Untill = DateTime.Now.Date
            };
            return View(vm);
        }
        [HttpPost]
        public IActionResult ExportDatabase(DateTime from, DateTime untill)
        {
            IQueryable<Bonos> bonos = _uow.BonosRepository.GetAll().Where(x=>x.Date>from&&x.Date<untill);
            ExportData export = new ExportData(bonos);
            return export.DownloadExcelDb();
        }
        [HttpPost]
        public async Task<IActionResult> ExportPdf(int id)
        {
            IQueryable<Bonos> bonos = _uow.BonosRepository.GetAll();
            ExportData export = new ExportData(bonos);
            return await export.PrintPdf(id);
        }
        public IActionResult DeleteAll()
        {
            return View();
        }
        [HttpPost]

Idea_Database_Interface/Controllers/UsersController.cs
using Idea_Database_Interface.Data;
using Idea_Database_Interface.Viewmodels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using NuGet.Common;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Idea_Database_Interface.Controllers
{
    [Authorize(Roles ="superadmin")]
    public class UsersController : Controller
    {
        private readonly IdeaDBContext _context;
        private UserManager<IdentityUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public UsersController(IdeaDBContext context, UserManager<IdentityUser> user, RoleManager<IdentityRole> role)
        {
            _context = context;
            _userManager = user;
            _roleManager = role;
            
        }
        //shows a list of all the users in the database
        public IActionResult Index()
        {
            UsuariosListViewModel model = new UsuariosListViewModel()
            {
                Users = _userManager.Users.ToList(),
                RoleManager = _roleManager,
                UserManager = _userManager

            };

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //deletes the selected user from the database
        public async Task<IActionResult> DeleteUser(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
            }
            else
                ModelState.AddModelError("", "User not found");

            return RedirectToAction("Index");
        }
        //gives the admin role to the selected user
        public async Task<IActionResult> UserAddAdmin(string id)
        {
            IdentityRole role = await _roleManager.FindByNameAsync("admin");
            //if the admin role doesnt exist, creates it
            if (role == null) { await _roleManager.CreateAsync(new IdentityRole("admin")); role = await _roleManager.FindByNameAsync("admin"); }
            IdentityUser user = await _userManager.FindByIdAsync(id);            
            IdentityResult result = await _userManager.AddToRoleAsync(user, role.Name);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UserAddSuperAdmin(string id)
        {
            IdentityRole role = await _roleManager.FindByNameAsync("superadmin");
            //if the role doesnt exist, creates it
            if(role == null) { await _roleManager.CreateAsync(new IdentityRole("superadmin")); role = await _roleManager.FindByNameAsync("superadmin"); }
            IdentityUser user = await _userManager.FindByIdAsync(id);
            IdentityResult result = await _userManager.AddToRoleAsync(user, role.Name);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteSuperAdminRole(string id)
        {
            IdentityRole role = await _roleManager.FindByNameAsync("superadmin");
            IdentityUser user = await _userManager.FindByIdAsync(id);
            IdentityResult result = await _userManager.RemoveFromRoleAsync(user, role.Name);
            return RedirectToAction("Index");
        }
    }
}

Idea_Database_Interface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Idea</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Idea_Database_Interface.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav style="background-color: #f27d00" class="navbar navbar-dark navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a asp-controller="Home" asp-action="Index">
                    <img src="~/img/idea white.png" height="45" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon navbar-dark"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav nav-tabs flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Empresas</a>
                        </li>
                        <li class="nav-item" >
                            <a class="nav-link text-white" asp-area="" asp-controller="Comercios" asp-action="Index"><div style="margin: 0 5px 0 5px" class="row">Establecimientos </div><div style ="margin: 0 5px 0 5px" class="row">comerciales</div></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Targeta" asp-action="Index">Targeta Alzira</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Emprendedores" asp-action="Index">Emprendedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Bonos" asp-action="Index">Bonos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Index">Usuarios</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2023 - Idea_Database_Interface - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>