Idea_Database_Interface/Models/Comercios.cs
using System.ComponentModel.DataAnnotations;

namespace Idea_Database_Interface.Models
{
    public class Comercios
    {
        [Key] 
        public int Id { get; set; }
        public string NombreComercial { get; set; }
        public string IAE { get; set; }
        public string? CódigoFUC { get; set; }
        public string? Calle { get; set; }
        public string? Número { get; set; }
        public int? CódigoPostal { get; set; }
        public string? Provincia { get; set; }
        public string? Municipio { get; set; }
        public string? Localidad { get; set; }
        public string? TeléfonoFijo { get; set; }
        public string Móvi { get; set; }
        public string Email { get; set; }
        public string CIF { get; set; }
        public string? Contacto { get; set; }
    }
}

Idea_Database_Interface/Controllers/ComerciosController.cs
using Idea_Database_Interface.Data.UnitOfWork;
using Idea_Database_Interface.Models;
using Idea_Database_Interface.Viewmodels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using PagedList;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;

namespace Idea_Database_Interface.Controllers
{
    [Authorize(Roles = "admin")]
    public class ComerciosController : Controller
    {
        private readonly IUnitOfWork _uow;
        public ComerciosController(IUnitOfWork uow) { _uow = uow; }
        public IActionResult Index(string searchString, string filterSelect, int? page)
        {
            List<string> options = new();
            options.Add("Nombre");
            options.Add("CIF");
            options.Add("Email");
            SelectList filterOptions = new SelectList(options, filterSelect);
            IEnumerable<Comercios> comercios = _uow.ComerciosRepository.GetAll();

            //filters based on the input of the searchstring and the selected filter
            //if the search string is empty it will just show all the companies
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                switch (filterSelect)
                {
                    case "Nombre":
                        comercios = comercios.Where(x => x.NombreComercial.ToLower().Contains(searchString));
                        break;
                    case "CIF":
                        comercios = comercios.Where(x => x.CIF.Contains(searchString));
                        break;
                    case "Email":
                        comercios = comercios.Where(x => x.Email.ToLower().Contains(searchString));
                        break;
                    default:
                        break;
                };
            }
            //This is to prevent the searchbox from being erased
            ViewBag.SearchString = searchString;
            int pageNumber = page ?? 1;
            int pageSize = 10;
            //this is to check if the pagenumber isnt higher than the pagecount
            IPagedList testList = comercios.ToPagedList(1, pageSize);
            if (testList.PageCount < pageNumber)
                pageNumber = testList.PageCount;
            pageNumber = pageNumber < 1 ? 1 : pageNumber;
            ComerciosListViewModel vm = new ComerciosListViewModel()
            {
                Comercios = comercios.ToPagedList(pageNumber, pageSize),
                FilterOptions = filterOptions,
                PageCount = pageNumber,
                SearchedFilter = filterSelect,
                SearchedString = searchString
            };
            //This resets the pagenumber for the next and previous page buttons
            //Without this you can only change the page once
            //And now it just works, i dont know how
            ModelState.Clear();
            return View(vm);
        }

        public IActionResult CreateComer()
        {
            ComerciosCrudViewModel vm = new ComerciosCrudViewModel();
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComer(ComerciosCrudViewModel model)
        {
            if (ModelState.IsValid)
            {
                _uow.ComerciosRepository.Create(new Comercios()
                {
                    NombreComercial = model.NombreComercial,
                    CIF = model.CIF,
                    IAE = model.IAE,
                    CódigoFUC = model.CódigoFUC,
                    Móvi = model.Móvi,
                    Calle = model.Calle,
                    Número = model.Número,
                    CódigoPostal = model.CódigoPostal,
                    Provincia = model.Provincia,
                    Municipio = model.Municipio,
                    Localidad = model.Localidad,
                    TeléfonoFijo = model.TeléfonoFijo,
                    Email = model.Email,
                    Contacto = model.Contacto
                });
                await _uow.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Details(int id)
        {
            ComercioDetailViewModel model = new ComercioDetailViewModel()
            {
                Comercio = await _uow.ComerciosRepository.GetById(id)
            };
            return View(model);
        }
        public async Task<IActionResult> UpdateComer(int id)
        {
            Comercios temp = await _uow.ComerciosRepository.GetById(id);
            ComerciosCrudViewModel model = new()
            {
                Calle = temp.Calle,
                CIF = temp.CIF,
                CódigoFUC = temp.CódigoFUC,
                Provincia = temp.Provincia,
                CódigoPostal = temp.CódigoPostal,
                NombreComercial = temp.NombreComercial,
                Email = temp.Email,
                IAE = temp.IAE,
                Id = id,
                Localidad = temp.Localidad,
                Municipio = temp.Municipio,
                Móvi = temp.Móvi,
                Número = temp.Número,
                TeléfonoFijo = temp.TeléfonoFijo,
                Contacto = temp.Contacto
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateComer(int id, ComerciosCrudViewModel model)
        {
            model.Id = id;
            if (ModelState.IsValid)
            {
                try
                {
                    Comercios comercio = new Comercios()
                    {
                        Calle = model.Calle,
                        CIF = model.CIF,
                        CódigoFUC = model.CódigoFUC,
                        Provincia = model.Provincia,
                        CódigoPostal = model.CódigoPostal,
                        NombreComercial = model.NombreComercial,
                        Email = model.Email,
                        IAE = model.IAE,
                        Id = id,
                        Localidad = model.Localidad,
                        Municipio = model.Municipio,
                        Móvi = model.Móvi,
                        Número = model.Número,
                        TeléfonoFijo = model.TeléfonoFijo,
                        Contacto = model.Contacto
                    };
                    _uow.ComerciosRepository.Update(comercio);
                    await _uow.Save();
                }
                catch (DBConcurrencyException ex)
                {
                    if (await _uow.ComerciosRepository.GetById(id) == null)
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction("Details", new { id = id });
            }
            return View(model);
        }
        public async Task<IActionResult> DeleteComer(int id)
        {
            ComercioDetailViewModel model = new ComercioDetailViewModel() { Comercio = await _uow.ComerciosRepository.GetById(id) };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteComer(int id, ComercioDetailViewModel model)
        {
            Comercios comer = await _uow.ComerciosRepository.GetById(id);
            if (comer != null)
            {
                _uow.ComerciosRepository.Delete(comer);
                await _uow.Save();
            }
            else
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Idea_Database_Interface/Views/Comercios/CreateComer.cshtml
@model Idea_Database_Interface.Viewmodels.ComerciosCrudViewModel
@{
    ViewData["Title"] = "Crear comercio";
}
<h1 class="mt-5">@ViewData["Title"]</h1>
<div class="row mt-8">
    <form asp-action="CreateComer" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="col-md-8">
            <div class="form-group" style="padding: 10px">
                <label asp-for="NombreComercial" class="control-label">Nombre comercial <span class="text-danger">*</span></label>
                <input asp-for="NombreComercial" class="form-control" />
                <span asp-validation-for="NombreComercial" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="IAE" class="control-label">IAE <span class="text-danger">*</span></label>
                <input asp-for="IAE" class="form-control" />
                <span asp-validation-for="IAE" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="Email" class="control-label">@Html.DisplayNameFor(model => this.Model.Email) <span class="text-danger">*</span></label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="CIF" class="control-label">@Html.DisplayNameFor(model => this.Model.CIF) <span class="text-danger">*</span></label>
                <input asp-for="CIF" class="form-control" />
                <span asp-validation-for="CIF" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="CódigoFUC" class="control-label">Código FUC</label>
                <input asp-for="CódigoFUC" class="form-control" />
                <span asp-validation-for="CódigoFUC" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="TeléfonoFijo" class="control-label">Teléfono Fijo</label>
                <input asp-for="TeléfonoFijo" class="form-control" />
                <span asp-validation-for="TeléfonoFijo" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="Móvi" class="control-label">@Html.DisplayNameFor(model => this.Model.Móvi) <span class="text-danger">*</span></label>
                <input type="text" asp-for="Móvi" class="form-control" />
                <span asp-validation-for="Móvi" class="text-danger"></span>
            </div>
            <div class="form-group row" style="padding: 10px">
                <div class="col-md-6">
                    <label asp-for="Calle" class="control-label">@Html.DisplayNameFor(model => this.Model.Calle)</label>
                    <input asp-for="Calle" class="form-control" />
                    <span asp-validation-for="Calle" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Número" class="control-label">@Html.DisplayNameFor(model => this.Model.Número)</label>
                    <input type="number" asp-for="Número" class="form-control" />
                    <span asp-validation-for="Número" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row" style="padding: 10px">
                <div class="col-md-6">
                    <label asp-for="CódigoPostal" class="control-label">@Html.DisplayNameFor(model => this.Model.CódigoPostal)</label>
                    <input asp-for="CódigoPostal" class="form-control" />
                    <span asp-validation-for="CódigoPostal" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Provincia" class="control-label">@Html.DisplayNameFor(model => this.Model.Provincia)</label>
                    <input asp-for="Provincia" class="form-control" />
                    <span asp-validation-for="Provincia" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row" style="padding: 10px">
                <div class="col-md-6">
                    <label asp-for="Municipio" class="control-label">@Html.DisplayNameFor(model => this.Model.Municipio)</label>
                    <input asp-for="Municipio" class="form-control" />
                    <span asp-validation-for="Municipio" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Localidad" class="control-label">@Html.DisplayNameFor(model => this.Model.Localidad)</label>
                    <input asp-for="Localidad" class="form-control      />
                    <span asp-validation-for="Localidad" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Contacto" class="control-label">Persona de contacto</label>
                    <input asp-for="Contacto" class="form-control       />
                    <span asp-validation-for="Contacto" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="form-group" style="padding: 10px">
                <input type="submit" value="Crear" class="btn" style="background-color: aqua !important; color: white !important;" />
                <a asp-action="Index" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
            </div>
        </div>
    </form>
</div>

Idea_Database_Interface/Views/Comercios/DeleteComer.cshtml
@model Idea_Database_Interface.Viewmodels.ComercioDetailViewModel
@{

}
<h2>Estás seguro de que quieres borrar el Comercio de @Model.Comercio.Nombre?</h2>
<form asp-action="DeleteComer" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger" />
    <a asp-controller="Comercios" asp-action="Details" asp-route-id="@Model.Comercio.Id" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
    <input type="submit" value="Borrar" asp-action="DeleteComer" asp-route-id="@Model.Comercio.Id" class="btn btn-danger" />
</form>

Idea_Database_Interface/Views/Comercios/Details.cshtml
@model Idea_Database_Interface.Viewmodels.ComercioDetailViewModel
@{
    ViewData["Title"] = "Comercio detalles ";
}
<h1>@Model.Comercio.Nombre</h1>
<br />
<p>IAE: @Model.Comercio.IAE</p>
<p>Código FUC: @Model.Comercio.CódigoFUC</p>
<p>Tipo de via: @Model.Comercio.TipoDeVia</p>
<p>Dirección: @Model.Comercio.Dirección</p>
<p>Teléfono Fijo: @Model.Comercio.TeléfonoFijo</p>
<p>Teléfono móvil: @Model.Comercio.TeléfonoMóvil</p>
<p>Correo: @Model.Comercio.Correo</p>
<br/>
<a class="btn" style="background-color: dodgerblue" asp-action="UpdateComer" asp-route-id="@Model.Comercio.Id">Actualización</a>
<a asp-action="DeleteComer" asp-route-id="@Model.Comercio.Id" class="btn btn-danger">Borrar</a>

Idea_Database_Interface/Views/Comercios/Index.cshtml
@model Idea_Database_Interface.Viewmodels.ComerciosListViewModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewData["Title"] = "Comercios";
}

<div>
    <h1 class="display-4">Comercios</h1>
    <br />
    @using (Html.BeginForm())
    {
        <div class="container">
            <div class="form-group row">
                <div class="col-md-4">
                    @Html.DropDownList("FilterSelect",Model.FilterOptions, null,new {@class="form-select flex-column", @id="selectFilter"})
                </div>
                <div class="col-md-4">
                    @Html.TextBox("SearchString",ViewBag.SearchString as string,new {@class="form-control"})
                    @*This is to reset the page to page 1 if you searched something new*@
                    @Html.Hidden("Page",null)
                </div>
                <div class="col-md-4">
                    <input type="submit" value="Filtro" class="btn input-group" style="background-color: darkorange" />
                </div>
            </div>
            <br />
            <div class="row justify-content-md-center">
                <a asp-action="CreateComer" class="btn col-md-3" style="background-color: darkorange">Crear uno nuevo comercio</a>
                <p class="text-end">Total: @Model.Comercios.TotalItemCount Comercios</p>
            </div>
        </div>
    }
    <div class="text-start">
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre comercial</th>
                    <th scope="col" class="d-none d-sm-table-cell">IAE</th>
                    <th scope="col" class="d-none d-sm-table-cell">Móvi</th>
                    <th scope="col" class="d-none d-sm-table-cell">Correo</th>
                    <th scope="col" class="d-none d-sm-table-cell">CIF</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comp in Model.Comercios)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem=>comp.NombreComercial)</td>
                        <td scope="col" class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem=>comp.IAE)</td>
                        <td scope="col" class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem=>comp.Móvi)</td>
                        <td scope="col" class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem=>comp.Email)</td>
                        <td scope="col" class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem=>comp.CIF)</td>
                        <td><a class="btn" style="background-color: dodgerblue" asp-action="Details" asp-route-id="@comp.Id">Detalles</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-md-3 d-flex">
        <div style="margin: 5px">
            @using (Html.BeginForm(FormMethod.Get))
            {
                @Html.Hidden("Page",1)
                @Html.Hidden("SearchString",Model.SearchedString)
                @Html.Hidden("FilterSelect", Model.SearchedFilter)
                <input type="submit" value="1" class="btn input-group btn-primary btn-sm" />
            }
        </div>
        <div style="margin: 5px">
            @using (Html.BeginForm(FormMethod.Get))
            {
                @Html.Hidden("Page",(Model.PageCount)-1)
                @Html.Hidden("SearchString",Model.SearchedString)
                @Html.Hidden("FilterSelect", Model.SearchedFilter)
                <input type="submit" value="<<" class="btn input-group btn-primary btn-sm" />
            }
        </div>
        <span style="margin: 5px">
            Page @(Model.Comercios.PageCount
            < Model.Comercios.PageNumber ? 0 : Model.Comercios.PageNumber) of @Model.Comercios.PageCount
        </span>
        <div style="margin: 5px">
            @using (Html.BeginForm(FormMethod.Get))
            {
                @Html.Hidden("Page", (Model.PageCount)+1)
                @Html.Hidden("SearchString",Model.SearchedString)
                @Html.Hidden("FilterSelect", Model.SearchedFilter)
                <input type="submit" value=">>" class="btn input-group btn-primary btn-sm" />
            }
        </div>
        @if (Model.Comercios.PageCount > 1)
        {
            <div style="margin: 5px">
                @using (Html.BeginForm(FormMethod.Get))
                {
                    @Html.Hidden("Page",Model.Comercios.PageCount)
                    @Html.Hidden("SearchString",Model.SearchedString)
                    @Html.Hidden("FilterSelect", Model.SearchedFilter)
                    <input type="submit" value="@Model.Comercios.PageCount" class="btn input-group btn-primary btn-sm" />
                }
            </div>
        }
    </div>
</div>

Idea_Database_Interface/Views/Comercios/UpdateComer.cshtml
@model Idea_Database_Interface.Viewmodels.ComerciosCrudViewModel
@{
    ViewData["Title"] = "Actualizar comercio";
}
<h1 class="mt-5">@ViewData["Title"]</h1>
<div class="row mt-8">
    <form asp-action="UpdateComer" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="col-md-8">
            <div class="form-group" style="padding: 10px">
                <label asp-for="Nombre" class="control-label">Nombre comercial <span class="text-danger">*</span></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="IAE" class="control-label">IAE <span class="text-danger">*</span></label>
                <input asp-for="IAE" class="form-control" />
                <span asp-validation-for="IAE" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="Correo" class="control-label">@Html.DisplayNameFor(model => this.Model.Correo) <span class="text-danger">*</span></label>
                <input type="email" asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="CódigoFUC" class="control-label">Código FUC <span class="text-danger">*</span></label>
                <input asp-for="CódigoFUC" class="form-control" />
                <span asp-validation-for="CódigoFUC" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="TeléfonoFijo" class="control-label">Teléfono Fijo</label>
                <input asp-for="TeléfonoFijo" class="form-control" />
                <span asp-validation-for="TeléfonoFijo" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="TeléfonoMóvil" class="control-label">Teléfono Móvil</label>
                <input type="text" asp-for="TeléfonoMóvil" class="form-control" />
                <span asp-validation-for="TeléfonoMóvil" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="Dirección" class="control-label">@Html.DisplayNameFor(model => this.Model.Dirección) <span class="text-danger">*</span></label>
                <input asp-for="Dirección" class="form-control" />
                <span asp-validation-for="Dirección" class="text-danger"></span>
            </div>

            <br />
            <div class="form-group" style="padding: 10px">
                <input type="submit" value="Crear" class="btn" style="background-color: aqua !important; color: white !important;" />
                <a asp-action="Index" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
            </div>
        </div>
    </form>
</div>