Idea_Database_Interface/Controllers/CategoriasController.cs
using Idea_Database_Interface.Data.UnitOfWork;
using Idea_Database_Interface.Models;
using Idea_Database_Interface.Viewmodels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;
using PagedList;
using System.Data;

namespace Idea_Database_Interface.Controllers
{
    [Authorize(Roles = "admin")]
    [Route("Emprendedores/Categorias/{action}")]
    public class CategoriasController : Controller
    {
        private readonly IUnitOfWork _uow;
        public CategoriasController(IUnitOfWork uow) { _uow = uow; }

        public IActionResult Index()
        {
            CategoriasListViewModel vm = new()
            {
                Categorias = _uow.CategoriaRepository.GetAll().ToList(),
                EmprendedoresCategorias = _uow.EmprendedoresCategoriaRepository.GetAll().ToList(),
                CatYears = _uow.CatYearRepository.GetAll().ToList()
            };
            return View(vm);
        }
        public IActionResult CreateCateg()
        {
            CategoriaCrudViewModel vm = new CategoriaCrudViewModel()
            {
                Years = new SelectList(_uow.CatYearRepository.GetAll(), "Id", "Nombre")
            };
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCateg(CategoriaCrudViewModel model)
        {
            if (ModelState.IsValid)
            {
                _uow.CategoriaRepository.Create(new Categoría()
                {
                    Nombre = model.Nombre,
                    IdYear = model.Year,
                    IsActive = model.IsActive
                });
                await _uow.Save();
                return RedirectToAction("Index");
            }
            else
            {
                model.Years = new SelectList(_uow.CatYearRepository.GetAll(), "Id", "Nombre");
                return View(model);
            }
        }
        public async Task<IActionResult> Overview(int id, string searchString, string filterSelect,int? page)
        {
            IEnumerable<Emprendedores> allEmps = _uow.EmprendedoresRepository.GetAll();
            List<EmprendedoresCategoría> emps = _uow.EmprendedoresCategoriaRepository.GetAll().Where(i => i.IdCategoría == id).ToList();
            List<Emprendedores> filtered = new List<Emprendedores>();
            //add all the emprendedores based on the category id
            foreach (var emp in emps)
            {
                Emprendedores temp = await _uow.EmprendedoresRepository.GetById(emp.IdEmprendedores);
                filtered.Add(temp);
            }
            //filters based on the input of the searchstring and the selected filter
            //if the search string is empty it will just show all 
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                switch (filterSelect)
                {
                    case "Nombre":
                        filtered = filtered.Where(x => x.Nombre.ToLower().Contains(searchString) || x.Apellidos.ToLower().Contains(searchString)).ToList();
                        break;
                    case "Teléfono":
                        filtered = filtered.Where(x => x.Teléfono.Contains(searchString)).ToList();
                        break;
                    case "Email":
                        filtered = filtered.Where(x => x.Email.ToLower().Contains(searchString)).ToList();
                        break;
                    default:
                        break;
                }
            }
            List<string> options = new();
            options.Add("Nombre");
            options.Add("Teléfono");
            options.Add("Email");
            SelectList filterOptions = new SelectList(options);
            //This is to prevent the searchbox from being erased
            ViewBag.SearchString = searchString;
            int pageNumber = page ?? 1;
            int pageSize = 10;
            //this is to check if the pagenumber isnt higher than the pagecount
            IPagedList testList = filtered.ToPagedList(1, pageSize);
            if (testList.PageCount < pageNumber)
                pageNumber = testList.PageCount;
            pageNumber = pageNumber < 1 ? 1 : pageNumber;
            CategoriaEmprendListViewModel vm = new CategoriaEmprendListViewModel()
            {
                Categoría = await _uow.CategoriaRepository.GetById(id),
                Emprendedores = filtered.ToPagedList(pageNumber,pageSize),
                FilterOptions = filterOptions,
                PageCount = pageNumber,
                SearchedFilter = filterSelect,
                SearchedString = searchString
            };
            //This resets the pagenumber for the next and previous page buttons
            //Without this you can only change the page once
            //And now it just works, i dont know how
            ModelState.Clear();
            return View(vm);
        }

        public IActionResult CreateYear()
        {
            CatYearCreateViewModel vm = new CatYearCreateViewModel();
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateYear(CatYearCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                _uow.CatYearRepository.Create(new CatYear()
                {
                    Nombre = model.Nombre
                });
                await _uow.Save();
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        public IActionResult Activar()
        {
            CategoriasListViewModel vm = new()
            {
                Categorias = _uow.CategoriaRepository.GetAll().ToList(),
                EmprendedoresCategorias = _uow.EmprendedoresCategoriaRepository.GetAll().ToList(),
                CatYears = _uow.CatYearRepository.GetAll().ToList()
            };
            return View(vm);
        }
        public async Task<IActionResult> ActivateCat(int id)
        {
            Categoría categoría = await _uow.CategoriaRepository.GetById(id);
            categoría.IsActive = !categoría.IsActive;
            _uow.CategoriaRepository.Update(categoría);
            await _uow.Save();
            return RedirectToAction("Activar");
        }
        public async Task<IActionResult> UpdateCateg(int id)
        {
            Categoría cat = await _uow.CategoriaRepository.GetById(id);
            CategoriaCrudViewModel vm = new CategoriaCrudViewModel()
            {
                Nombre = cat.Nombre,
                Id = id,
                IsActive = cat.IsActive,
                Year = cat.IdYear,
                Years = new SelectList(_uow.CatYearRepository.GetAll(), "Id", "Nombre")
            };
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCateg(int id, CategoriaCrudViewModel model)
        {
            model.Id = id;
            if (ModelState.IsValid)
            {
                _uow.CategoriaRepository.Update(new Categoría()
                {
                    Nombre = model.Nombre,
                    IdYear = model.Year,
                    IsActive = model.IsActive,
                    Id = (int)model.Id
                });
                await _uow.Save();
                return RedirectToAction("Activar");
            }
            else
            {
                model.Years = new SelectList(_uow.CatYearRepository.GetAll(), "Id", "Nombre");
                return View(model);
            }
        }
    }
}

Idea_Database_Interface/Controllers/EmprendedoresController.cs
using Idea_Database_Interface.Data.UnitOfWork;
using Idea_Database_Interface.Models;
using Idea_Database_Interface.Viewmodels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using System.Data;
using PagedList;

namespace Idea_Database_Interface.Controllers
{
    [Authorize(Roles = "admin")]
    public class EmprendedoresController : Controller
    {
        private readonly IUnitOfWork _uow;
        public EmprendedoresController(IUnitOfWork uow) { _uow = uow; }
        public List<Categoría> Categorias;

        public IActionResult Index(string searchString, string filterSelect, int? page)
        {
            Categorias = _uow.CategoriaRepository.GetAll().ToList();
            IEnumerable<Emprendedores> emprendes = _uow.EmprendedoresRepository.GetAll().Include(p => p.Categorías).OrderByDescending(x => x.Fecha);
            List<string> options = new();
            options.Add("Nombre");
            options.Add("Teléfono");
            options.Add("Email");
            SelectList filterOptions = new SelectList(options);
            //filters based on the input of the searchstring and the selected filter
            //if the search string is empty it will just show all the companies
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                switch (filterSelect)
                {
                    case "Nombre":
                        emprendes= emprendes.Where(x => x.Nombre.ToLower().Contains(searchString) || x.Apellidos.ToLower().Contains(searchString)).ToList();
                        break;
                    case "Teléfono":
                        emprendes = emprendes.Where(x => x.Teléfono.Contains(searchString)).ToList();
                        break;
                    case "Email":
                        emprendes = emprendes.Where(x => x.Email.ToLower().Contains(searchString)).ToList();
                        break;
                    default:
                        break;
                }
            }
            //This is to prevent the searchbox from being erased
            ViewBag.SearchString = searchString;
            int pageNumber = page ?? 1;
            int pageSize = 10;
            //this is to check if the pagenumber isnt higher than the pagecount
            IPagedList testList = emprendes.ToPagedList(1, pageSize);
            if (testList.PageCount < pageNumber)
                pageNumber = testList.PageCount;
            pageNumber = pageNumber < 1 ? 1 : pageNumber;
            EmprendedoresListViewModel vm = new()
            {
                Emprendedores = emprendes.ToPagedList(pageNumber,pageSize),
                FilterOptions = filterOptions,
                PageCount = pageNumber,
                SearchedFilter = filterSelect,
                SearchedString = searchString
            };
            //This resets the pagenumber for the next and previous page buttons
            //Without this you can only change the page once
            //And now it just works, i dont know how
            ModelState.Clear();
            return View(vm);

        }
        public IActionResult CreateEmprend()
        {
            EmprendedoresCrudViewModel vm = new()
            {
                //This code will fill the select box with all the categories.
                //It will show the name and the value that is connected is the id,
                //so it can be used to create the association link with the entrepeneur
                AllCategorias = new MultiSelectList(_uow.CategoriaRepository.GetAll().Where(x=>x.IsActive==true), "Id", "Nombre")
            };
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEmprend(EmprendedoresCrudViewModel model)
        {
            if (ModelState.IsValid)
            {
                _uow.EmprendedoresRepository.Create(new Emprendedores()
                {
                    Fecha = model.Fecha + model.FechaHora,
                    Nombre = model.Nombre,
                    Apellidos = model.Apellidos,
                    Teléfono = model.Teléfono,
                    Email = model.Email,
                    MotivoDeLaConsulto = model.MotivoDeLaConsulto,
                    Incidencias = model.Incidencias,
                    Observaciones = model.Observaciones,
                    PlanViabilidad = model.PlanViabilidad,
                    Terminado = model.Terminado
                });
                await _uow.Save();
                //The following code will add the categories to the freshly created entrepeneur.
                //It will also check to see if the categories are already linked.
                //Wich is redundant, so i will comment it
                Emprendedores updateCat = _uow.EmprendedoresRepository.GetAll()
                    .Where(p => p.Fecha == model.Fecha + model.FechaHora && p.Nombre == model.Nombre).FirstOrDefault();
                //IQueryable<EmprendedoresCategoría> check = _uow.EmprendedoresCategoriaRepository.GetAll();
                if (updateCat != null && model.SelectedCategorias != null)
                {
                    if (model.Categorias == null)
                        model.Categorias = new List<EmprendedoresCategoría>();
                    foreach (int item in model.SelectedCategorias)
                    {
                        EmprendedoresCategoría tempAdd = new()
                        {
                            Emprendedores = updateCat,
                            IdEmprendedores = updateCat.Id,
                            IdCategoría = item,
                            Categoría = await _uow.CategoriaRepository.GetById(item),
                        };
                        //if (check.Where(x => x.IdCategoría == tempAdd.IdCategoría && x.IdEmprendedores == tempAdd.IdEmprendedores) == null)
                        model.Categorias.Add(tempAdd);
                    }
                    updateCat.Categorías = model.Categorias;
                    _uow.EmprendedoresRepository.Update(updateCat);
                    await _uow.Save();
                }


                return RedirectToAction("Index");
            }
            else
            {
                model.AllCategorias = new MultiSelectList(_uow.CategoriaRepository.GetAll().Where(x=>x.IsActive==true), "Id", "Nombre");
                return View(model);
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            Categorias = _uow.CategoriaRepository.GetAll().ToList();
            EmprendedoresDetailsViewModel vm = new EmprendedoresDetailsViewModel()
            {
                Emprendedores = await _uow.EmprendedoresRepository.GetById(id),
                CatYears = _uow.CatYearRepository.GetAll().ToList()
            };
            vm.Emprendedores.Categorías = _uow.EmprendedoresCategoriaRepository.GetAll().Where(p => p.IdEmprendedores == id).Include(i => i.Categoría).ToList();
            return View(vm);
        }
        public async Task<IActionResult> UpdateEmprend(int id)
        {
            Emprendedores temp = await _uow.EmprendedoresRepository.GetById(id);
            //this code is to show the selected categories, but it doesnt work yet
            int[] selection = new int[] { };
            if (temp.Categorías != null)
            {
                foreach (var cat in temp.Categorías)
                {
                    selection.Append(cat.Id);
                }
            }

            EmprendedoresCrudViewModel vm = new EmprendedoresCrudViewModel()
            {
                Id = id,
                Apellidos = temp.Apellidos,
                Nombre = temp.Nombre,
                Email = temp.Email,
                Fecha = temp.Fecha,
                Incidencias = temp.Incidencias,
                MotivoDeLaConsulto = temp.Incidencias,
                Observaciones = temp.Observaciones,
                PlanViabilidad = temp.PlanViabilidad,
                Teléfono = temp.Teléfono,
                Terminado = temp.Terminado,
                AllCategorias = new MultiSelectList(_uow.CategoriaRepository.GetAll().Where(x => x.IsActive == true), "Id", "Nombre"),
                SelectedCategorias = selection
            };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateEmprend(EmprendedoresCrudViewModel model)
        {
            if (ModelState.IsValid)
            {
                _uow.EmprendedoresRepository.Update(new Emprendedores()
                {
                    Id = (int)model.Id,
                    Fecha = model.Fecha + model.FechaHora,
                    Nombre = model.Nombre,
                    Apellidos = model.Apellidos,
                    Teléfono = model.Teléfono,
                    Email = model.Email,
                    MotivoDeLaConsulto = model.MotivoDeLaConsulto,
                    Incidencias = model.Incidencias,
                    Observaciones = model.Observaciones,
                    PlanViabilidad = model.PlanViabilidad,
                    Terminado = model.Terminado
                });
                await _uow.Save();
                Emprendedores updateCat = await _uow.EmprendedoresRepository.GetById((int)model.Id);
                IQueryable<EmprendedoresCategoría> check = _uow.EmprendedoresCategoriaRepository.GetAll();
                //checks to see if the association is already in the database, otherwise it will add it
                if (updateCat != null && model.SelectedCategorias != null)
                {
                    if (model.Categorias == null)
                        model.Categorias = new List<EmprendedoresCategoría>();

Idea_Database_Interface/Views/Categorias/Activar.cshtml
@model Idea_Database_Interface.Viewmodels.CategoriasListViewModel
@{
    ViewData["Title"] = "Categorías página";
}
<h1 class="display-4">Categorías</h1>
<br />
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 d-flex">
            <a class="btn btn-primary input-group" style="margin: 5px;" asp-action="Index">Volver</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group list-group-flush">
                <li class="list-group-item list-group-item-dark d-flex justify-content-between align-items-center">
                    <span>Nombre</span>
                    <div>
                        <span>Activar |</span>
                        <span>Actualizar</span>
                    </div>
                </li>
                @foreach (var cat in Model.Categorias)
                {
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        @cat.Nombre
                        <div>
                            <a class="btn btn-outline-primary" asp-action="ActivateCat" asp-route-id="@cat.Id">
                                @if (cat.IsActive)
                                {
                                    <i class="bi bi-check2-square"></i>
                                }
                                else
                                {
                                    <i class="bi bi-app"></i>
                                }
                            </a>
                            <a class="btn btn-outline-warning" asp-action="UpdateCateg" asp-route-id="@cat.Id"><i class="bi bi-pencil-square"></i></a>
                        </div>
                    </li>
                }
            </ul>
        </div>

    </div>
</div>

Idea_Database_Interface/Views/Categorias/CreateCateg.cshtml
@model Idea_Database_Interface.Viewmodels.CategoriaCrudViewModel
@{
    ViewData["Title"] = "Crear categoría";
}
<h3 class="display-4">Crear una categoría</h3>
<br/>
<form asp-action="CreateCateg" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger" />
    <div class="col-md-8">
        <div class="form-group" style="margin: 10px">
            <label asp-for="Year" class="contol-label">Año <span class="text-danger">*</span></label>
            <select class="form-control" asp-items="Model.Years" asp-for="Year"></select>
        </div>
        <div class="form-group" style="margin: 10px">
            <label asp-for="Nombre" class="control-label">@Html.DisplayNameFor(model => this.Model.Nombre) <span class="text-danger">*</span></label>
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
        
        <div class="form-group" style="padding: 10px">
            <label asp-for="IsActive" class="form-check-label">Activo</label>
            <input type="checkbox" asp-for="IsActive" class="form-check-input" />
        </div>
        
    </div>
    <div class="form-group" style="margin: 10px">
        <input type="submit" value="Crear" class="btn" style="background-color: aqua !important; color: white !important;" />
        <a asp-controller="Categorias" asp-action="Index" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
    </div>
    <br />
    
</form>

Idea_Database_Interface/Views/Categorias/CreateYear.cshtml
@model Idea_Database_Interface.Viewmodels.CatYearCreateViewModel
@{
    ViewData["Title"] = "Crear año";
}
<h3 class="display-4">Crear año</h3>
<br />
<form asp-action="CreateYear" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger" />
    <div class="col-md-8">
        <div class="form-group" style="padding: 10px">
            <label asp-for="Nombre" class="control-label">@Html.DisplayNameFor(model => this.Model.Nombre) <span class="text-danger">*</span></label>
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
        <div class="form-group" style="padding: 10px">
            <input type="submit" value="Crear" class="btn" style="background-color: aqua !important; color: white !important;" />
            <a asp-controller="Categorias" asp-action="Index" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
        </div>
    </div>
</form>

Idea_Database_Interface/Views/Categorias/Index.cshtml
@model Idea_Database_Interface.Viewmodels.CategoriasListViewModel
@{
    ViewData["Title"] = "Categorías página";
}
<h1 class="display-4">Categorías</h1>
<br />
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 d-flex">
            <a class="btn btn-primary input-group" style="margin: 5px;" asp-action="CreateCateg">Crear categoría</a>
            <a class="btn btn-primary input-group" style="margin: 5px;" asp-action="CreateYear">Crear año</a>
            <a class="btn btn-primary input-group" style="margin: 5px;" asp-action="Activar">Actuaciones</a>
        </div>
    </div>
    <br />
    <div class="row">
        @foreach (var year in Model.CatYears)
        {
            <div class="col-md-4">
                <h4>@year.Nombre</h4>
                <ul class="list-group list-group-flush">
                    @foreach (var cat in Model.Categorias.Where(x => x.IdYear == year.Id))
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a class="nav-link text-black" asp-action="Overview" asp-route-id="@cat.Id">@cat.Nombre</a>
                            @if (@Model.EmprendedoresCategorias.Where(x => x.IdCategoría == cat.Id).Count() < 20)
                            {
                                <span class="badge bg-primary ">@Model.EmprendedoresCategorias.Where(x=>x.IdCategoría==cat.Id).Count()</span>
                            }
                            else
                            {
                                <span class="badge bg-success ">@Model.EmprendedoresCategorias.Where(x=>x.IdCategoría==cat.Id).Count()</span>
                            }
                        </li>
                    }
                </ul>
            </div>
        }
    </div>

</div>

Idea_Database_Interface/Views/Categorias/Overview.cshtml
@model Idea_Database_Interface.Viewmodels.CategoriaEmprendListViewModel
@{
    ViewData["Title"] = "Emprendedores página";
}
<h1 class="display-4">@Model.Categoría.Nombre</h1>
<br />
@using (Html.BeginForm())
{
    <div class="container">
        <div class="form-group row">
            <div class="col-md-4">
                @Html.DropDownList("FilterSelect",Model.FilterOptions, null,new {@class="form-select flex-column", @id="selectFilter"})
            </div>
            <div class="col-md-4">
                @Html.TextBox("SearchString",ViewBag.SearchString as string,new {@class="form-control"})
                @*This is to reset the page to page 1 if you searched something new*@
                @Html.Hidden("Page",null)
            </div>
            <div class="col-md-4">
                <input type="submit" value="Filtro" class="btn input-group" style="background-color: darkorange" />
            </div>
        </div>
        <br />
        <div class="row justify-content-md-center">
            <div class="col-md-3">
                <a asp-controller="Emprendedores" asp-action="CreateEmprend" class="btn input-group" style="background-color: darkorange">Crear una nuevo emprendedor</a>
            </div>
            <div class="col-md-3">
                <a asp-controller="Categorias" asp-action="Index" class="btn input-group" style="background-color: darkorange">Categorías</a>
            </div>
            <p class="text-end">Total: @Model.Emprendedores.TotalItemCount Emprendedores</p>
        </div>
    </div>
}
<div>
    <table class="table ">
        <thead>
            <tr>
                <th>Nombre</th>
                <th scope="col" class="d-none d-sm-table-cell">Dia</th>
                <th scope="col" class="d-none d-sm-table-cell">Hora</th>
                <th scope="col" style="width:fit-content" class="d-none d-sm-table-cell">Teléfono</th>
                <th scope="col" class="d-none d-sm-table-cell">Email</th>
                <th scope="col" class="d-none d-sm-table-cell">Motivo de la consulta</th>
                <th scope="col" class="d-none d-sm-table-cell">Plan de viabilidad</th>
                <th scope="col" class="d-none d-sm-table-cell">Terminado</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Emprendedores)
            {
                <tr>
                    <td>@item.Nombre @item.Apellidos</td>
                    <td scope="col" class="d-none d-sm-table-cell">@item.Fecha.Date.ToString("d")</td>
                    <td scope="col" class="d-none d-sm-table-cell">@item.Fecha.TimeOfDay</td>
                    <td scope="col" style="width: 10%" class="d-none d-sm-table-cell">@item.Teléfono</td>
                    <td scope="col" class="d-none d-sm-table-cell">@item.Email</td>
                    <td scope="col" class="d-none d-sm-table-cell">@item.MotivoDeLaConsulto</td>
                    <td scope="col" class="d-none d-sm-table-cell">
                        @if (item.PlanViabilidad)
                        {
                            <div class="text-center">
                                <p>&#10004</p>
                            </div>
                        }
                        else
                        {
                            <div class="text-center">
                                <p>&times</p>
                            </div>
                        }
                    </td>
                    <td scope="col" class="d-none d-sm-table-cell">
                        @if (item.Terminado)
                        {
                            <div class="text-center">
                                <p>&#10004</p>
                            </div>
                        }
                        else
                        {
                            <div class="text-center">
                                <p>&times</p>
                            </div>
                        }
                    </td>
                    <td>
                        <a class="btn" style="background-color: dodgerblue" asp-controller="Emprendedores" asp-action="Details" asp-route-id="@item.Id">Detalles</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <div class="col-md-3 d-flex">
        <div>
            @using (Html.BeginForm(FormMethod.Get))
            {
                @Html.Hidden("Page",(Model.PageCount)-1)
                @Html.Hidden("SearchString",Model.SearchedString)
                @Html.Hidden("FilterSelect", Model.SearchedFilter)
                <input type="submit" value="<<" class="btn input-group btn-primary btn-sm" />
            }
        </div>
        <span style="margin: 5px">
            Page @(Model.Emprendedores.PageCount
            < Model.Emprendedores.PageNumber ? 0 : Model.Emprendedores.PageNumber) of @Model.Emprendedores.PageCount
        </span>
        <div>
            @using (Html.BeginForm(FormMethod.Get))
            {
                @Html.Hidden("Page", (Model.PageCount)+1)
                @Html.Hidden("SearchString",Model.SearchedString)
                @Html.Hidden("FilterSelect", Model.SearchedFilter)
                <input type="submit" value=">>" class="btn input-group btn-primary btn-sm" />
            }
        </div>
    </div>
</div>

Idea_Database_Interface/Views/Categorias/UpdateCateg.cshtml
@model Idea_Database_Interface.Viewmodels.CategoriaCrudViewModel
@{
    ViewData["Title"] = "Actualizar categoría";
}
<h3 class="display-4">Actualizar esta categoría</h3>
<br />
<form asp-action="UpdateCateg" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger" />
    <div class="col-md-8">
        <div class="form-group" style="margin: 10px">
            <label asp-for="Year" class="contol-label">Año <span class="text-danger">*</span></label>
            <select class="form-control" asp-items="Model.Years" asp-for="Year"></select>
        </div>
        <div class="form-group" style="margin: 10px">
            <label asp-for="Nombre" class="control-label">@Html.DisplayNameFor(model => this.Model.Nombre) <span class="text-danger">*</span></label>
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>

        <div class="form-group" style="padding: 10px">
            <label asp-for="IsActive" class="form-check-label">Activo</label>
            <input type="checkbox" asp-for="IsActive" class="form-check-input" />
        </div>

    </div>
    <div class="form-group" style="padding: 10px">
        <input type="submit" value="Actualizar" asp-route-id="@Model.Id" class="btn" style="background-color: aqua !important; color: white !important;" />
        <a asp-controller="Categorias" asp-action="Activar" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
    </div>
    <br />

</form>