Idea_Database_Interface/Models/Targeta.cs
using System.ComponentModel.DataAnnotations;

namespace Idea_Database_Interface.Models
{
    public class Targeta
    {
        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string IAE { get; set; }
        public string CódigoFUC { get; set;}
        public string TipoDeVia { get; set; }
        public string Dirección { get; set; }
        public string? TeléfonoFijo { get; set; }
        public string? TeléfonoMóvil { get; set; }
        public string? Correo { get; set; }
    }
}

Idea_Database_Interface/Controllers/TargetaController.cs
using Idea_Database_Interface.Data.UnitOfWork;
using Idea_Database_Interface.Models;
using Idea_Database_Interface.Viewmodels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PagedList;
using System.Data;

namespace Idea_Database_Interface.Controllers
{
    public class TargetaController : Controller
    {
        private readonly IUnitOfWork _uow;
        public TargetaController(IUnitOfWork uow) { _uow = uow; }
        public IActionResult Index(string searchString, string filterSelect, int? page)
        {
            List<string> options = new();
            options.Add("Nombre");
            options.Add("FUC");
            options.Add("Correo");
            SelectList filterOptions = new SelectList(options, filterSelect);
            IEnumerable<Targeta> targetas = _uow.TargetasRepository.GetAll();

            //filters based on the input of the searchstring and the selected filter
            //if the search string is empty it will just show all the companies
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                switch (filterSelect)
                {
                    case "Nombre":
                        targetas = targetas.Where(x => x.Nombre.ToLower().Contains(searchString));
                        break;
                    case "CIF":
                        targetas = targetas.Where(x => x.CódigoFUC.Contains(searchString));
                        break;
                    case "Email":
                        targetas = targetas.Where(x => x.Correo.ToLower().Contains(searchString));
                        break;
                    default:
                        break;
                };
            }
            //This is to prevent the searchbox from being erased
            ViewBag.SearchString = searchString;
            int pageNumber = page ?? 1;
            int pageSize = 10;
            //this is to check if the pagenumber isnt higher than the pagecount
            IPagedList testList = targetas.ToPagedList(1, pageSize);
            if (testList.PageCount < pageNumber)
                pageNumber = testList.PageCount;
            pageNumber = pageNumber < 1 ? 1 : pageNumber;
            TargetaListViewModel vm = new TargetaListViewModel()
            {
                Targetas = targetas.ToPagedList(pageNumber, pageSize),
                FilterOptions = filterOptions,
                PageCount = pageNumber,
                SearchedFilter = filterSelect,
                SearchedString = searchString
            };
            //This resets the pagenumber for the next and previous page buttons
            //Without this you can only change the page once
            //And now it just works, i dont know how
            ModelState.Clear();
            return View(vm);
        }
        public IActionResult CreateTargeta()
        {
            TargetaCrudViewModel vm = new TargetaCrudViewModel();
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTargeta(TargetaCrudViewModel model)
        {
            if (ModelState.IsValid)
            {
                _uow.TargetasRepository.Create(new Targeta()
                {
                    Nombre = model.Nombre,
                    IAE = model.IAE,
                    CódigoFUC = model.CódigoFUC,
                    TeléfonoMóvil = model.TeléfonoMóvil,
                    TipoDeVia = model.TipoDeVia,
                    Dirección = model.Dirección,
                    TeléfonoFijo = model.TeléfonoFijo,
                    Correo = model.Correo
                });
                await _uow.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Details(int id)
        {
            TargetaDetailViewModel model = new TargetaDetailViewModel()
            {
                Targeta = await _uow.TargetasRepository.GetById(id)
            };
            return View(model);
        }
        public async Task<IActionResult> UpdateTargeta(int id)
        {
            Targeta model = await _uow.TargetasRepository.GetById(id);
            TargetaCrudViewModel vm = new()
            {
                Id = id,
                Nombre = model.Nombre,
                IAE = model.IAE,
                CódigoFUC = model.CódigoFUC,
                TeléfonoMóvil = model.TeléfonoMóvil,
                TipoDeVia = model.TipoDeVia,
                Dirección = model.Dirección,
                TeléfonoFijo = model.TeléfonoFijo,
                Correo = model.Correo
            };
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTargeta(int id, TargetaCrudViewModel model)
        {
            model.Id = id;
            if (ModelState.IsValid)
            {
                try
                {
                    Targeta targeta = new Targeta()
                    {
                        Id = id,
                        Nombre = model.Nombre,
                        IAE = model.IAE,
                        CódigoFUC = model.CódigoFUC,
                        TeléfonoMóvil = model.TeléfonoMóvil,
                        TipoDeVia = model.TipoDeVia,
                        Dirección = model.Dirección,
                        TeléfonoFijo = model.TeléfonoFijo,
                        Correo = model.Correo
                    };
                    _uow.TargetasRepository.Update(targeta);
                    await _uow.Save();
                }
                catch (DBConcurrencyException ex)
                {
                    if (await _uow.TargetasRepository.GetById(id) == null)
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction("Details", new { id = id });
            }
            return View(model);
        }
        public async Task<IActionResult> DeleteTargeta(int id)
        {
            TargetaDetailViewModel model = new TargetaDetailViewModel() { Targeta = await _uow.TargetasRepository.GetById(id) };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTargeta(int id, TargetaDetailViewModel model)
        {
            Targeta targeta = await _uow.TargetasRepository.GetById(id);
            if (targeta != null)
            {
                _uow.TargetasRepository.Delete(targeta);
                await _uow.Save();
            }
            else
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Idea_Database_Interface/Views/Targeta/CreateTargeta.cshtml
@model Idea_Database_Interface.Viewmodels.TargetaCrudViewModel
@{
    ViewData["Title"] = "Crear comercio";
}
<h1 class="mt-5">@ViewData["Title"]</h1>
<div class="row mt-8">
    <form asp-action="CreateTargeta" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="col-md-8">
            <div class="form-group" style="padding: 10px">
                <label asp-for="Nombre" class="control-label">Nombre comercial <span class="text-danger">*</span></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="IAE" class="control-label">IAE <span class="text-danger">*</span></label>
                <input asp-for="IAE" class="form-control" />
                <span asp-validation-for="IAE" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="Correo" class="control-label">@Html.DisplayNameFor(model => this.Model.Correo) <span class="text-danger">*</span></label>
                <input type="email" asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="CódigoFUC" class="control-label">Código FUC <span class="text-danger">*</span></label>
                <input asp-for="CódigoFUC" class="form-control" />
                <span asp-validation-for="CódigoFUC" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="TeléfonoFijo" class="control-label">Teléfono Fijo</label>
                <input asp-for="TeléfonoFijo" class="form-control" />
                <span asp-validation-for="TeléfonoFijo" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="TeléfonoMóvil" class="control-label">Teléfono Móvil</label>
                <input type="text" asp-for="TeléfonoMóvil" class="form-control" />
                <span asp-validation-for="TeléfonoMóvil" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="Dirección" class="control-label">@Html.DisplayNameFor(model => this.Model.Dirección) <span class="text-danger">*</span></label>
                <input asp-for="Dirección" class="form-control" />
                <span asp-validation-for="Dirección" class="text-danger"></span>
            </div>

            <br />
            <div class="form-group" style="padding: 10px">
                <input type="submit" value="Crear" class="btn" style="background-color: aqua !important; color: white !important;" />
                <a asp-action="Index" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
            </div>
        </div>
    </form>
</div>

Idea_Database_Interface/Views/Targeta/DeleteTargeta.cshtml
@model Idea_Database_Interface.Viewmodels.TargetaDetailViewModel
@{

}
<h2>Estás seguro de que quieres borrar el Comercio de @Model.Targeta.Nombre?</h2>
<form asp-action="DeleteTargeta" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger" />
    <a asp-controller="Targeta" asp-action="Details" asp-route-id="@Model.Targeta.Id" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
    <input type="submit" value="Borrar" asp-action="DeleteTargeta" asp-route-id="@Model.Targeta.Id" class="btn btn-danger" />
</form>

Idea_Database_Interface/Views/Targeta/Details.cshtml
@model Idea_Database_Interface.Viewmodels.TargetaDetailViewModel
@{
    ViewData["Title"] = "Targeta detalles ";
}
<h1>@Model.Targeta.Nombre</h1>
<br />
<p>IAE: @Model.Targeta.IAE</p>
<p>Código FUC: @Model.Targeta.CódigoFUC</p>
<p>Tipo de via: @Model.Targeta.TipoDeVia</p>
<p>Dirección: @Model.Targeta.Dirección</p>
<p>Teléfono Fijo: @Model.Targeta.TeléfonoFijo</p>
<p>Teléfono móvil: @Model.Targeta.TeléfonoMóvil</p>
<p>Correo: @Model.Targeta.Correo</p>
<br />
<a class="btn" style="background-color: dodgerblue" asp-action="UpdateTargeta" asp-route-id="@Model.Targeta.Id">Actualización</a>
<a asp-action="DeleteTargeta" asp-route-id="@Model.Targeta.Id" class="btn btn-danger">Borrar</a>

Idea_Database_Interface/Views/Targeta/Index.cshtml
@model Idea_Database_Interface.Viewmodels.TargetaListViewModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewData["Title"] = "Establecimientos comerciales";
}

<div>
    <h1 class="display-4">Targeta Alzira</h1>
    <br />
    @using (Html.BeginForm())
    {
        <div class="container">
            <div class="form-group row">
                <div class="col-md-4">
                    @Html.DropDownList("FilterSelect",Model.FilterOptions, null,new {@class="form-select flex-column", @id="selectFilter"})
                </div>
                <div class="col-md-4">
                    @Html.TextBox("SearchString",ViewBag.SearchString as string,new {@class="form-control"})
                    @*This is to reset the page to page 1 if you searched something new*@
                    @Html.Hidden("Page",null)
                </div>
                <div class="col-md-4">
                    <input type="submit" value="Filtro" class="btn input-group" style="background-color: darkorange" />
                </div>
            </div>
            <br />
            <div class="row justify-content-md-center">
                <a asp-action="CreateTargeta" class="btn col-md-3" style="background-color: darkorange">Crear uno nuevo comercio</a>
                <p class="text-end">Total: @Model.Targetas.TotalItemCount Targetas</p>
            </div>
        </div>
    }
    <div class="text-start">
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre comercial</th>
                    <th scope="col" class="d-none d-sm-table-cell">IAE</th>
                    <th scope="col" class="d-none d-sm-table-cell">Teléfono Móvil</th>
                    <th scope="col" class="d-none d-sm-table-cell">Correo</th>
                    <th scope="col" class="d-none d-sm-table-cell">FUC</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comp in Model.Targetas)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem=>comp.Nombre)</td>
                        <td scope="col" class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem=>comp.IAE)</td>
                        <td scope="col" class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem=>comp.TeléfonoMóvil)</td>
                        <td scope="col" class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem=>comp.Correo)</td>
                        <td scope="col" class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem=>comp.CódigoFUC)</td>
                        <td><a class="btn" style="background-color: dodgerblue" asp-action="Details" asp-route-id="@comp.Id">Detalles</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-md-3 d-flex">
        <div style="margin: 5px">
            @using (Html.BeginForm(FormMethod.Get))
            {
                @Html.Hidden("Page",1)
                @Html.Hidden("SearchString",Model.SearchedString)
                @Html.Hidden("FilterSelect", Model.SearchedFilter)
                <input type="submit" value="1" class="btn input-group btn-primary btn-sm" />
            }
        </div>
        <div style="margin: 5px">
            @using (Html.BeginForm(FormMethod.Get))
            {
                @Html.Hidden("Page",(Model.PageCount)-1)
                @Html.Hidden("SearchString",Model.SearchedString)
                @Html.Hidden("FilterSelect", Model.SearchedFilter)
                <input type="submit" value="<<" class="btn input-group btn-primary btn-sm" />
            }
        </div>
        <span style="margin: 5px">
            Page @(Model.Targetas.PageCount
            < Model.Targetas.PageNumber ? 0 : Model.Targetas.PageNumber) of @Model.Targetas.PageCount
        </span>
        <div style="margin: 5px">
            @using (Html.BeginForm(FormMethod.Get))
            {
                @Html.Hidden("Page", (Model.PageCount)+1)
                @Html.Hidden("SearchString",Model.SearchedString)
                @Html.Hidden("FilterSelect", Model.SearchedFilter)
                <input type="submit" value=">>" class="btn input-group btn-primary btn-sm" />
            }
        </div>
        @if (Model.Targetas.PageCount > 1)
        {
            <div style="margin: 5px">
                @using (Html.BeginForm(FormMethod.Get))
                {
                    @Html.Hidden("Page",Model.Targetas.PageCount)
                    @Html.Hidden("SearchString",Model.SearchedString)
                    @Html.Hidden("FilterSelect", Model.SearchedFilter)
                    <input type="submit" value="@Model.Targetas.PageCount" class="btn input-group btn-primary btn-sm" />
                }
            </div>
        }
    </div>
</div>

Idea_Database_Interface/Views/Targeta/UpdateTargeta.cshtml
@model Idea_Database_Interface.Viewmodels.TargetaCrudViewModel
@{
    ViewData["Title"] = "Actualizar comercio";
}
<h1 class="mt-5">@ViewData["Title"]</h1>
<div class="row mt-8">
    <form asp-action="UpdateTargeta" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="col-md-8">
            <div class="form-group" style="padding: 10px">
                <label asp-for="Nombre" class="control-label">Nombre comercial <span class="text-danger">*</span></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="IAE" class="control-label">IAE <span class="text-danger">*</span></label>
                <input asp-for="IAE" class="form-control" />
                <span asp-validation-for="IAE" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="Correo" class="control-label">@Html.DisplayNameFor(model => this.Model.Correo) <span class="text-danger">*</span></label>
                <input type="email" asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="CódigoFUC" class="control-label">Código FUC <span class="text-danger">*</span></label>
                <input asp-for="CódigoFUC" class="form-control" />
                <span asp-validation-for="CódigoFUC" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="TeléfonoFijo" class="control-label">Teléfono Fijo</label>
                <input asp-for="TeléfonoFijo" class="form-control" />
                <span asp-validation-for="TeléfonoFijo" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="TeléfonoMóvil" class="control-label">Teléfono Móvil</label>
                <input type="text" asp-for="TeléfonoMóvil" class="form-control" />
                <span asp-validation-for="TeléfonoMóvil" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding: 10px">
                <label asp-for="Dirección" class="control-label">@Html.DisplayNameFor(model => this.Model.Dirección) <span class="text-danger">*</span></label>
                <input asp-for="Dirección" class="form-control" />
                <span asp-validation-for="Dirección" class="text-danger"></span>
            </div>

            <br />
            <div class="form-group" style="padding: 10px">
                <input type="submit" value="Crear" class="btn" style="background-color: aqua !important; color: white !important;" />
                <a asp-action="Index" class="btn" style="background-color: aqua !important; color: white !important;">Volver</a>
            </div>
        </div>
    </form>
</div>